"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

from NtdPlayer import appVersion


APP = ['NtdPlayer.py']
DATA_FILES = []
PKGS = ['listener', 'menu', 'parser', 'queue', 'tkDnD']
MODULES = ['gui', 'clipInfo']
RESOURCES = ['icons', 'tkdnd2.7', 'bin']
OPTIONS = {
    'argv_emulation': True,
    'iconfile': 'ntdplayer_512.icns',
    'plist': {'CFBundleShortVersionString': appVersion, 'NSHumanReadableCopyright': 'Copyright (C) 2002-2015  NTDTV'},
    'packages': PKGS,
    'includes': MODULES,
    'resources': RESOURCES
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
